import type { Issue } from './types';

export const issues: Issue[] = [
  {
    id: '1',
    title: 'Poste de luz queimado na Quadra 15',
    description: 'O poste em frente ao lote 23 está com a lâmpada queimada há mais de uma semana, deixando a rua muito escura e perigosa à noite.',
    category: 'Iluminação Pública',
    status: 'Resolvido',
    location: { lat: -15.983, lng: -48.024 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-05-10T09:00:00Z'),
    reporter: 'Maria Silva',
  },
  {
    id: '2',
    title: 'Buraco perigoso na avenida principal',
    description: 'Existe um buraco grande e fundo no meio da Avenida Central, próximo ao cruzamento com a Rua 5. Vários carros já quase caíram nele.',
    category: 'Buracos na Via',
    status: 'Em análise',
    location: { lat: -15.985, lng: -48.026 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-05-20T14:30:00Z'),
    reporter: 'João Pereira',
  },
  {
    id: '3',
    title: 'Lixo acumulado em terreno baldio',
    description: 'O terreno ao lado da escola infantil está com uma quantidade enorme de lixo e entulho, atraindo insetos e animais.',
    category: 'Lixo Acumulado',
    status: 'Recebido',
    location: { lat: -15.981, lng: -48.028 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-05-22T11:20:00Z'),
    reporter: 'Ana Costa',
  },
  {
    id: '4',
    title: 'Placa de "PARE" caída',
    description: 'A placa de "PARE" no cruzamento da Rua 12 com a Rua 8 caiu e está no chão, causando confusão no trânsito.',
    category: 'Sinalização Danificada',
    status: 'Recebido',
    location: { lat: -15.987, lng: -48.022 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-05-23T08:00:00Z'),
    reporter: 'Carlos Souza',
  },
   {
    id: '5',
    title: 'Vazamento de água limpa',
    description: 'Há um vazamento de água na calçada da Quadra 2, desperdiçando muita água e deixando o local escorregadio.',
    category: 'Vazamento de Água',
    status: 'Em análise',
    location: { lat: -15.986, lng: -48.030 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-05-18T17:00:00Z'),
    reporter: 'Fernanda Lima',
  },
  {
    id: '6',
    title: 'Semáforo de pedestres com defeito',
    description: 'O semáforo para pedestres na faixa em frente ao hospital não está funcionando, o que torna a travessia muito perigosa.',
    category: 'Sinalização Danificada',
    status: 'Resolvido',
    location: { lat: -15.982, lng: -48.027 },
    imageUrl: 'https://placehold.co/600x400.png',
    reportedAt: new Date('2024-04-28T10:15:00Z'),
    reporter: 'Ricardo Alves',
  },
];
