import type { Issue } from './types';

// This file is now a backup and will not be actively used for display.
// Data is fetched from Firestore. This is used to seed the database.

export const issues: Omit<Issue, 'id' | 'reportedAt'>[] = [
  {
    title: 'Poste de luz queimado na Quadra 15',
    description: 'O poste em frente ao lote 23 está com a lâmpada queimada há mais de uma semana, deixando a rua muito escura e perigosa à noite.',
    category: 'Iluminação pública',
    status: 'Resolvido',
    location: { lat: -16.001, lng: -47.985 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Maria Silva',
    upvotes: 15,
  },
  {
    title: 'Buraco perigoso na avenida principal',
    description: 'Existe um buraco grande e fundo no meio da Avenida Central, próximo ao cruzamento com a Rua 5. Vários carros já quase caíram nele.',
    category: 'Buracos na via',
    status: 'Em análise',
    location: { lat: -16.004, lng: -47.988 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'João Pereira',
    upvotes: 32,
  },
  {
    title: 'Lixo acumulado na praça central',
    description: 'As lixeiras da praça central estão transbordando e o lixo está se espalhando pela calçada. O cheiro está muito forte.',
    category: 'Lixo acumulado',
    status: 'Recebido',
    location: { lat: -16.005, lng: -47.986 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Ana Costa',
    upvotes: 21,
  },
  {
    title: 'Sinal de trânsito com defeito',
    description: 'O semáforo do cruzamento da Rua 10 com a Avenida Brasil está piscando amarelo sem parar há dois dias, causando confusão no trânsito.',
    category: 'Sinalização danificada',
    status: 'Em análise',
    location: { lat: -16.002, lng: -47.991 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Carlos Souza',
    upvotes: 8,
  },
  {
    title: 'Vazamento de água limpa',
    description: 'Há um vazamento de água potável na calçada da Quadra 2, que está desperdiçando muita água e já formou uma poça grande.',
    category: 'Vazamento de água',
    status: 'Resolvido',
    location: { lat: -15.999, lng: -47.989 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Fernanda Lima',
    upvotes: 45,
  },
  {
    title: 'Calçada quebrada na Quadra 10',
    description: 'A calçada em frente à padaria está toda quebrada, dificultando a passagem de pedestres, principalmente idosos e pessoas com carrinhos de bebê.',
    category: 'Buracos na via',
    status: 'Recebido',
    location: { lat: -16.008, lng: -47.982 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Mariana Almeida',
    upvotes: 12,
  },
  {
    title: 'Terreno baldio com mato alto',
    description: 'O terreno ao lado da escola infantil está com o mato muito alto, o que pode atrair animais peçonhentos e gerar insegurança.',
    category: 'Outros',
    status: 'Em análise',
    location: { lat: -16.006, lng: -47.993 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Ricardo Nunes',
    upvotes: 5,
  },
  {
    title: 'Falta de iluminação no parque',
    description: 'O parque da cidade fica completamente escuro à noite, tornando-o inutilizável e perigoso para os moradores.',
    category: 'Iluminação pública',
    status: 'Recebido',
    location: { lat: -16.010, lng: -47.987 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Beatriz Santos',
    upvotes: 18,
  },
    {
    title: 'Bueiro entupido na Rua das Flores',
    description: 'O bueiro na esquina da Rua das Flores com a Av. Principal está entupido e, sempre que chove, a rua alaga completamente.',
    category: 'Vazamento de água',
    status: 'Em análise',
    location: { lat: -16.003, lng: -47.984 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Lucas Martins',
    upvotes: 25,
  },
  {
    title: 'Placa de "Pare" pichada',
    description: 'A placa de "Pare" no cruzamento perigoso da Quadra 5 está completamente pichada e ilegível, aumentando o risco de acidentes.',
    category: 'Sinalização danificada',
    status: 'Resolvido',
    location: { lat: -16.007, lng: -47.990 },
    imageUrl: 'https://placehold.co/600x400.png',
    reporter: 'Juliana Ribeiro',
    upvotes: 9,
  },
];
